version: '2'
services:
  transaction_app:
    mem_limit: 256000000
    command: ./uwsgi.sh
    environment:
      AWS_REGION: us-west-2
      AWS_XRAY_DAEMON_ADDRESS: 'aws-xray-daemon:2000'
    links:
      - aws-xray-daemon
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: transaction_app
  transaction_nginx:
    mem_limit: 128000000
    links:
      - transaction_app
    ports:
      - '0:80'
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: transaction_nginx
  aws-xray-daemon:
    image: 'amazon/aws-xray-daemon'
    mem_limit: 128000000
    ports:
      - '0:2000/udp'
    command:
      - "/usr/bin/xray"
      - "--bind"
      - "0.0.0.0:2000"
      - "--region"
      - "us-west-2"
      - "--buffer-memory"
      - "64"
      - "--log-level"
      - "dev"
      - "--log-file"
      - "/dev/stdout"
    logging:
      driver: awslogs
      options:
        awslogs-group: msa_app
        awslogs-region: us-west-2
        awslogs-stream-prefix: transaction_xray-daemon
